name: Auto Approve UI/UX PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:
    inputs:
      pr:
        description: "PR number to approve"
        required: true

permissions:
  contents: read
  pull-requests: write

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - name: Approve PR with BOT_PAT (ui-ux/*)
        if: ${{ secrets.BOT_PAT != '' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.BOT_PAT }}
          script: |
            const isDispatch = context.eventName === 'workflow_dispatch';
            const prNumber = isDispatch ? Number(core.getInput('pr')) : context.payload.pull_request.number;
            if (!prNumber) {
              core.setFailed('No PR number resolved');
              return;
            }
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            });
            if (!isDispatch && !pr.head.ref.startsWith('ui-ux/')) {
              core.info(`Skip: head ref ${pr.head.ref} not ui-ux/*`);
              return;
            }
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              event: 'APPROVE',
              body: 'Auto-approve UI/UX PR via workflow to satisfy branch protection.'
            });
            core.info(`Approved PR #${prNumber}`);

      - name: Skip approval (no BOT_PAT configured)
        if: ${{ secrets.BOT_PAT == '' }}
        uses: actions/github-script@v7
        with:
          script: |
            core.info('BOT_PAT secret not configured; skipping auto-approval to avoid self-approval error.')
