name: Auto Fix Lint & Format (UI/UX)

on:
  push:
    branches:
      - 'ui-ux/**'
      - 'feat/ui-ux-*'

permissions:
  contents: write

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_PAT || secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Run ESLint --fix
        run: npx eslint . --fix --ignore-pattern .github/workflows || true
      - name: Run Prettier write
        run: npx prettier --write . '!**/.github/workflows/**' || true
      - name: Commit changes (if any)
        env:
          BOT_PAT: ${{ secrets.BOT_PAT }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore: auto-fix lint & format"
            if [ -n "$BOT_PAT" ]; then
              git remote set-url origin https://x-access-token:$BOT_PAT@github.com/${{ github.repository }}
            else
              git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/${{ github.repository }}
            fi
            git push
          else
            echo "No changes to commit"
          fi
